name: pytask-parallel

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >= 0.0.11
  - cloudpickle
  - loky

  # pytask package dependencies
  - attrs >=17.4.0
  - click
  - click-default-group
  - networkx >=2.4
  - pluggy
  - pony >=0.7.13
  - rich

  # Misc
  - black
  - bump2version
  - jupyterlab
  - matplotlib
  - pdbpp
  - pre-commit
  - pytest-cov
  - versioneer

  # Documentation
  - numpydoc
  - pydata-sphinx-theme
  - sphinx
  - sphinx-copybutton
