name: pytask-parallel

channels:
  - conda-forge/label/pytask_rc
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - pytask>=0.4.0
  - cloudpickle
  - loky
  - optree

  # Misc
  - tox
  - ipywidgets
  - nbmake
  - pre-commit
  - pytest-cov

  - pip:
    - -e .
