name: pytask-parallel

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python
  - pip
  - setuptools_scm
  - toml

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >=0.3
  - cloudpickle
  - loky
  - pybaum >=0.1.1

  # Misc
  - black
  - pre-commit
  - pytest-cov

  - pip:
    - -e .
