name: pytask-parallel
channels:
  - conda-forge
  - pytask
dependencies:
  - python
  - pip

  # Conda
  - anaconda-client
  - conda-build
  - conda-verify

  # Package dependencies
  - pytask >= 0.0.5
  - cloudpickle

  # Misc
  - bump2version
  - jupyterlab
  - matplotlib
  - pdbpp
  - pre-commit
  - pytest-cov

  # Documentation
  - numpydoc
  - pydata-sphinx-theme
  - sphinx
  - sphinx-copybutton
